apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argo-cd
  annotations:
    argocd-image-updater.argoproj.io/image-list: registry.mecan.ir/devops_certification/argocd/flask-app:~1.0
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/update-strategy: newest-build
spec:
  project: default
  source:
    repoURL: https://github.com/AhmadRafiee/DevOps_Certification.git
    targetRevision: main
    path: argocd/flask-app
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
