replicaCount: 1

image:
  repository: registry.mecan.ir/devops_certification/argocd/flask-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000
  nodePort: 30050
