stages:
  - install
  - test

image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/cache/pip"

default:
  before_script:
    - "[ -d $PIP_CACHE_DIR ] || mkdir -p $PIP_CACHE_DIR"
    
  cache:
    key: pip-cache-${CI_COMMIT_REF_SLUG}
    paths:
      - $PIP_CACHE_DIR
    policy: pull-push

install:
  stage: install
  script:
    - ls $PIP_CACHE_DIR
    - pip install --no-compile --cache-dir $PIP_CACHE_DIR -r requirements.txt
    - du -sh $PIP_CACHE_DIR
    - ls $PIP_CACHE_DIR

test:
  stage: test
  script:
    - ls $PIP_CACHE_DIR
    - pip install --no-compile --cache-dir $PIP_CACHE_DIR -r requirements.txt
    - python script.py
    - du -sh $PIP_CACHE_DIR
    - ls $PIP_CACHE_DIR


##  requirements.txt
# openstacksdk
# docker
# requests